export const registerType=[
    {
        id:0,
        name:'aprt',
        data:'Apartment',
    },
    {
        id:1,
        name:'sec',
        data:'Security',
    },
    {
        id:2,
        name:'cus',
        data:'Customer',
    },
]
export const orderlist=[
    {
    "id":"84",
"booking_id":"BMRS-20240214-84",
"booking_date":"2024-02-14",
"customer_name":"Sangram keshari samanta",
"customer_mobile":"8796541230",
"passenger_count":"3",
"auto_code":"R1A010",
"driver_name":"ASGAR ALI SAHA",
"driver_mobile":"7992949036",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"JYB",
"drop_location":"Jaydevbihar",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t14/02/2024\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20240214-84\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A010 (OD02AJ 2702)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tJaydevbihar\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/14-02-2024/BMRS-20240214-84_1707904651.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"0",
"is_cancelled":"0",
"is_setteled":"0",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2024-02-14 15:27:31",
"updated_at":"2024-02-14 15:27:31",
"vehicle_rating":"0.00"
},
{
"id":"58",
"booking_id":"BMRS-20231213-58",
"booking_date":"2023-12-13",
"customer_name":"wer",
"customer_mobile":"8877923456",
"passenger_count":"3",
"auto_code":"123456",
"driver_name":"driver anme",
"driver_mobile":"9876543210",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"JYB",
"drop_location":"Jaydevbihar",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n\n<head>\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n\t<title>Prepaid Auto</title>\n</head>\n\n<body>\n\t<div\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\n\t\t\t<tr>\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-top: 20px;\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tDate:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-top: 20px;\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\t13/12/2023\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tTrip ID:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tBMRS-20231213-58\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\n\t\t\t\t\tAuto Unique Code:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\t123456 (or02br1510)\n\t\t\t\t</td>\n\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tFrom Location:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\n\t\t\t\t\tMaster Canteen Railway Station\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tTo Location:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tJaydevbihar\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\n\t\t\t\t\tNo. Of Passengers:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\t3\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\tAuto Type:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\n\t\t\t\t\t3 Seater\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\n\t\t\t\t\tTotal Fare:\n\t\t\t\t</th>\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\n\t\t\t\t\t300.00\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/13-12-2023/BMRS-20231213-58_1702472804.jpeg\" alt=\"qrcode\" width=\"100px\">\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\n\t\t\t\tpadding-bottom: 15px;\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\n\t\t\t\t\tScan the QR code to submit feedback\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>\n</body>\n\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"1",
"is_announced":"0",
"customer_feedback":"",
"customer_rating":"5",
"created_by":"1",
"created_at":"2023-12-13 18:36:44",
"updated_at":"2024-01-22 21:18:22",
"vehicle_rating":"5.00"
},
{
"id":"57",
"booking_id":"BMRS-20231213-57",
"booking_date":"2023-12-13",
"customer_name":"Susit Test",
"customer_mobile":"7456981235",
"passenger_count":"3",
"auto_code":"R1A006",
"driver_name":"PRASNNNA PRADHAN",
"driver_mobile":"9938950688",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"JYB",
"drop_location":"Jaydevbihar",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t13/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231213-57\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A006 (OD02AC2330)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tJaydevbihar\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/13-12-2023/BMRS-20231213-57_1702464062.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"0",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-13 16:11:02",
"updated_at":"2024-02-14 15:26:48",
"vehicle_rating":"0.00"
},
{
"id":"56",
"booking_id":"BMRS-20231213-56",
"booking_date":"2023-12-13",
"customer_name":"Test Test",
"customer_mobile":"8527419632",
"passenger_count":"3",
"auto_code":"R1A014",
"driver_name":"BALLABH KU ROUT",
"driver_mobile":"8908292635",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"PAT",
"drop_location":"Patia",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t13/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231213-56\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A014 (OR02AM6915)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tPatia\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/13-12-2023/BMRS-20231213-56_1702464039.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"1",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-13 16:10:39",
"updated_at":"2023-12-13 18:37:51",
"vehicle_rating":"0.00"
},
{
"id":"55",
"booking_id":"BMRS-20231213-55",
"booking_date":"2023-12-13",
"customer_name":"Test Smr",
"customer_mobile":"9638527416",
"passenger_count":"3",
"auto_code":"R1A024",
"driver_name":"OFFICER NAYAK",
"driver_mobile":"9556741744",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"PAT",
"drop_location":"Patia",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t13/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231213-55\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A024 (OR02AH2230)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tPatia\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/13-12-2023/BMRS-20231213-55_1702463811.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"0",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-13 16:06:51",
"updated_at":"2023-12-13 16:06:58",
"vehicle_rating":"0.00"
},
{
"id":"54",
"booking_id":"BMRS-20231213-54",
"booking_date":"2023-12-13",
"customer_name":"Smr Test",
"customer_mobile":"1234567895",
"passenger_count":"3",
"auto_code":"R1A001",
"driver_name":"AMINA NAYAK",
"driver_mobile":"8658325889",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"JYB",
"drop_location":"Jaydevbihar",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t13/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231213-54\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A001 (OD02P7321)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tJaydevbihar\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/13-12-2023/BMRS-20231213-54_1702463779.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"1",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-13 16:06:19",
"updated_at":"2023-12-13 16:07:08",
"vehicle_rating":"0.00"
},
{
"id":"53",
"booking_id":"BMRS-20231205-53",
"booking_date":"2023-12-05",
"customer_name":"Abheejit Panda ",
"customer_mobile":"9874569874",
"passenger_count":"3",
"auto_code":"R1A006",
"driver_name":"PRASNNNA PRADHAN",
"driver_mobile":"9938950688",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"JYB",
"drop_location":"Jaydevbihar",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t05/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231205-53\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A006 (OD02AC2330)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tJaydevbihar\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/05-12-2023/BMRS-20231205-53_1701763544.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"1",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-05 13:35:44",
"updated_at":"2023-12-05 14:55:41",
"vehicle_rating":"0.00"
},
{
"id":"52",
"booking_id":"BMRS-20231205-52",
"booking_date":"2023-12-05",
"customer_name":"Jyotiemayee Dash",
"customer_mobile":"8890503758",
"passenger_count":"3",
"auto_code":"R1A033",
"driver_name":"RABINDRA NAYAK",
"driver_mobile":"8018237307",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"PAT",
"drop_location":"Patia",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t05/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231205-52\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A033 (OD02C0501)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tPatia\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/05-12-2023/BMRS-20231205-52_1701761076.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"0",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-05 12:54:36",
"updated_at":"2023-12-05 14:55:22",
"vehicle_rating":"0.00"
},
{
"id":"51",
"booking_id":"BMRS-20231205-51",
"booking_date":"2023-12-05",
"customer_name":"Dibyajit Panda",
"customer_mobile":"9090075968",
"passenger_count":"3",
"auto_code":"R1A010",
"driver_name":"ASGAR ALI SAHA",
"driver_mobile":"7992949036",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"PAT",
"drop_location":"Patia",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t05/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231205-51\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A010 (OD02AJ 2702)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tPatia\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/05-12-2023/BMRS-20231205-51_1701761051.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"1",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-05 12:54:11",
"updated_at":"2023-12-05 14:55:44",
"vehicle_rating":"0.00"
},
{
"id":"50",
"booking_id":"BMRS-20231205-50",
"booking_date":"2023-12-05",
"customer_name":"Sushree Sahu",
"customer_mobile":"9348707234",
"passenger_count":"3",
"auto_code":"R1A002",
"driver_name":"MAGI NAYAK",
"driver_mobile":"8018867586",
"auto_category":"3 Seater",
"pickup_code":"BMRS",
"pickup_location":"Master Canteen Railway Station",
"drop_code":"JYB",
"drop_location":"Jaydevbihar",
"total_amount":"300.00",
"admin_amount":"15.00",
"driver_amount":"285.00",
"booking_voucher":"<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n\t<title>Prepaid Auto</title>\r\n</head>\r\n\r\n<body>\r\n\t<div\r\n\t\tstyle=\"margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;width:283px;padding-left:5px;padding-right:5px;padding-top:5px;padding-bottom:5px\">\r\n\t\t<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: auto;\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td style=\"padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:5px; text-align:center;font-family: Arial;border-bottom: 2px solid #000;\" colspan=\"2\">\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/prepaid-auto-bookings/assets/img/Thermal-Receipt-2.png\" alt=\"logo\" width=\"110px\">\r\n\t\t\t\t\t<h3 style=\"margin: 0;font-family: Arial;\">Prepaid Auto Stand</h3>\r\n\t\t\t\t\t<p style=\"margin: 0;font-family: Arial;font-size: 15px;\">Bhubaneswar,Odisha,751021</p>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tDate:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-top: 20px;\r\n\t\t\t\tpadding-bottom: 10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t05/12/2023\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTrip ID:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tBMRS-20231205-50\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;white-space: nowrap;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Unique Code:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tR1A002 (OD02N8396)\r\n\t\t\t\t</td>\r\n\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tFrom Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tMaster Canteen Railway Station\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tTo Location:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tJaydevbihar\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;white-space: nowrap;\" >\r\n\t\t\t\t\tNo. Of Passengers:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;text-align: left;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\tAuto Type:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:10px;font-family: Arial;font-size: 15px;\" >\r\n\t\t\t\t\t3 Seater\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;text-align: left;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\tTotal Fare:\r\n\t\t\t\t</th>\r\n\t\t\t\t<td style=\"padding-right:10px;padding-top:5px;padding-bottom:20px;font-family: Arial;font-size: 15px;border-bottom: 2px dashed #b7b7b7;\" >\r\n\t\t\t\t\t300.00\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center;border-bottom: 2px dashed #b7b7b7;padding-top: 6px;\" colspan=\"2\" >\r\n\t\t\t\t\t<img src=\"http://88.208.224.110/bbsr-prepaid-auto-booking/api/V1/documents/05-12-2023/BMRS-20231205-50_1701761017.jpeg\" alt=\"qrcode\" width=\"100px\">\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t<td style=\"text-align:center; color:#b7b7b7;font-family: Arial;font-size: 15px;padding-top: 15px;\r\n\t\t\t\tpadding-bottom: 15px;\r\n\t\t\t\tfont-weight: 500;\" colspan=\"2\" >\r\n\t\t\t\t\tScan the QR code to submit feedback\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n\r\n</html>",
"is_trip_end":"1",
"is_cancelled":"0",
"is_setteled":"1",
"is_announced":"0",
"customer_feedback":null,
"customer_rating":"0",
"created_by":"1",
"created_at":"2023-12-05 12:53:37",
"updated_at":"2023-12-05 14:55:36",
"vehicle_rating":"0.00"
}
]