export default {
  ADDON_BOOKING: 'Addon Booking',
  LOGOUT: 'Logout',
  LOGOUT_TEXT: 'Are you sure want to logout?',
  LOGIN: 'Guest Sign In',
  VERIFICATION:'Verification',
  VERIFICATION_CODE:'Enter the verification code send to you',
  STARTSAT: 'Starts at',
  FILTER_PRICE: 'Price',
  SORTING: 'Sorting',
  FILTER_HEADING: 'Sort & Filters',
  REVIEWS: 'Reviews',
  REVIEW: 'Review',
  TERMS_AND_CONDITIONS_ACCEPT: 'I have read and accept the',
  CREATE_ACCOUNT:'I agree to create my account.',
  TERMS_AND_CONDITIONS: 'Terms and Conditions',
  RECOMMENDED: 'Recommended for you',
  PARTNER: 'Partners',
  REVIEW_SCORE: 'Review Score',
  No_RESULTS_FOUND: 'No Results Found',
  NO_NOTIFICATION_FOUND: 'No Notifications Found',

  SEND_OTP: 'Send OTP',


  //Home
  SEE_ALL: 'See all',
  HOLIDAY_PACKAGE: 'Holiday Package',
  NEXT_TRIPS: 'Get Inspiration for Next Trip',
  TOP_BOOKINGS: 'Top Reservations',
  UNLOCK_WONDERS: 'Discover the Best Kept Secrets',
  HOME_SEARCH: 'Search Hotel, Rentals, Packages...',
  // HOME_SEARCH: 'Search Hotel, Rentals, Ticketing...',
  //Drawer
  LOGIN_JOIN: 'Login/Join',
  HOTEL: 'Hotel',
  ECO: 'Eco Retreat',
  RENTALS: 'Rentals',
  HOLIDAY: 'Holiday Package',
  TICKETING: 'Ticketing',
  ODISHA_WALK: 'Odisha Walks',
  CONTACT: 'Contact',
  //orderdetails
  ORDER_DETAILS: 'Order Details',

  SINGLE_OCCUPANCY: 'Single occupancy',
  DOUBLE_OCCUPANCY: 'Double occupancy',
  TRPLE_OCCUPANCY: 'Triple occupancy',

  // Order Review Strings
  PLACEHOLDER_FIRST_NAME: 'First Name',
  PLACEHOLDER_LAST_NAME: 'Last Name',
  PLACEHOLDER_EMAIL: 'Email',
  PLACEHOLDER_PHONE: 'Phone',
  PLACEHOLDER_ADDRESS1: 'Address line 1 *',
  PLACEHOLDER_ADDRESS2: 'Address line 2',
  PLACEHOLDER_SEARCH_COUNTRY: 'Search Country',
  PLACEHOLDER_SEARCH_STATE: 'Search For State/Province/Region',
  PLACEHOLDER_SEARCH_CITY: 'Search City',
  PLACEHOLDER_ZIP: 'ZIP code/Postal code*',
  EXPECTED_ARIVAL_TIME: '9:30 AM',
  EXPECTED_ARIVAL_TIME__: 'Expected Arrival Time',
  SPECIAL_REQUIREMENT: 'Special Requirements',
  PLACEHOLDER_REGISTRATION: 'Registration Number',
  PLACEHOLDER_COMPANY: 'Registration Company Name*',
  PLACEHOLDER_COMP_ADDRESS: 'Registration Company Address*',
  // rental
  PICKUP_DATE_TIME: ' Pickup Date & Time',
  DROP_DATE_TIME: 'Drop Date & Time',
  DROP_LOCATION: 'Drop Location',
  PICKUP_LOCATION: 'Pickup Location',
  ADD_DROP_LOCATION: 'Add Drop Location',
  PICKUP_CITY: 'Pickup City',
  DROP_CITY: 'Drop City',

  VENDOR: 'Vendor',
  NIGHT: 'Night',
  NIGHTS: 'Nights',
  CHECK_OUT: 'Check Out',
  CHECK_IN: 'Check In',
  PAYMENT_BREAKUP: 'PAYMENT BREAKUP',
  HOTEL_SELL_PRICE: 'Hotel Sell Price',
  EXTRA_ADULT_CHILD_CHARGE: 'Extra Adult / Child Charges',
  GROSS_PRICE: 'Gross Price',
  DISCOUNT: 'Discount',
  SUB_TOTAL_PRICE: 'Sub Total Price',
  TOTAL_AMOUNT: 'Total Amount',
  COUPON_CODES: 'COUPON CODES',
  HAVE_A_COUPON_CODE: 'Have a Coupon Code?',
  COUPON_APPLIED: 'Coupon Applied',
  GUIDE_CHARGE: 'Guide Charge:',
  SPECIAL_DISCOUNT: 'Discount',
  SELECT_ROOM:'SELECT ROOM',

  NAME: 'Name*',
  EMAIL: 'Email*',
  PHONE: 'Phone*',
  ADDRESS1: 'Address line 1*',
  ADDRESS2: 'Address line 2',
  COUNTRY: 'Country',
  SELECT_COUNTRY: 'Select Country',
  SELECT_STATE_PRO_REGION: 'Select State/Province/Region',
  SELECT_STATE_PRO_REGION__: 'Select State/Province/Region*',
  SELECT_COUNTRY_FIRST: 'Select Country First',
  SELECT_CITY: 'Select City',
  SELECT_STATE_FIRST: 'Select State First',
  ZIP: 'ZIP code/Postal code*',
  ZIP_: 'ZIP code/Postal code',
  DOYOU_NEED_PICKUP: 'Do you need Pickup?',
  VECHILE_DEPART: 'Vehicle will depart at 10AM from Panthanivas Bhubaneswar',
  ENTER_GST_DETAILS: 'Enter GST Details (Optional for Business Profile)',
  REGISTRATION_NUMBER: 'Registration Number*',
  REGISTERED_COMPANY_NAME: 'Registered Company Name*',
  REGISTERED_COMPANY_ADDRESS: 'Registered Company Address*',
  PAYMENT_METHOD: 'Select Payment Method',
  BOOK_NOW: 'BOOK NOW',
  CITY__: 'City*',
  NORMAL_CITY:"City",

  BOOKING_SUBMISSION: 'BOOKING DETAILS',

  QUANTITY: 'Quantity:',


  //Login
  MOBILE_MAIL_PLACEHOLDER: 'Enter mobile number',
  VERIFY_OTP: 'Verify OTP',
  EMAIL_LOGIN_WITHOUTSTAR: 'Email',
  PASSWORD_LOGIN: 'Password',

  ADULT_TICKET: 'Adult Ticket',
  CHILD_TICKET: 'Child Ticket',

  START_TIME: 'Start Time',
  END_TIME: 'End Time',

  LOGIN_T0_UNLOCK_SECRET_DEAL:
    'Login to preefilled prefilled user details &  Unlock a secret deal!',
  LOGIN_TEXT: 'LOGIN',
  REVIEW_LOGIN_BUTTON: 'Login to review',
  STAR_CATEGORY: 'Star Category',
  USER_RATING: 'User Rating',
  SEATER: 'Seater',
  NO_ORDERS_FOUND: 'No Orders Found',
  DETAILS: 'More Details',
  ROOM_DETAILS: 'Room Details',

  BOOKING_CONFIRAMATION_VOUCHER: 'Booking Confirmation Voucher',
  NOREVIEW_FOUND: 'No Reviews Found',

  FILTER: 'FILTER',
  SORT:'SORT'
};
